[package]
name = "flooder"
version = "0.1.0"
authors = ["ZaWarudo <ZaWaaarudo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.0"
yaml-rust = "0.4.3"
futures = "0.3.5"